# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.117.129:3306/mybatis_learn?characterEncoding=utf-8&useSSL=false
    username: root
    password: Rise@12345


mybatis-plus:
  #日志实现
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 全局配置
    db-config:
      # 数据库配置-id的生成策略
      id-type: ASSIGN_ID
  mapper-locations: classpath:/mapper/**.xml
